<a href="https://colab.research.google.com/github/muneshchandra08/data-science-practice/blob/main/numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x = np.array([40,67,57,90])
x, type(x)

(array([40, 67, 57, 90]), numpy.ndarray)

In [4]:
x.ndim

1

In [5]:
x.shape , x.size

((4,), 4)

In [6]:
y = x.reshape(2,2)
y

array([[40, 67],
       [57, 90]])

In [7]:
n = x.reshape(4)
n

array([40, 67, 57, 90])

In [8]:
y.ndim, y.shape

(2, (2, 2))

In [9]:
c = np.arange(3,9)
c

array([3, 4, 5, 6, 7, 8])

In [10]:
c.reshape(3,2), c.dtype

(array([[3, 4],
        [5, 6],
        [7, 8]]),
 dtype('int64'))

In [11]:
c.astype(float),c.astype(str)

(array([3., 4., 5., 6., 7., 8.]),
 array(['3', '4', '5', '6', '7', '8'], dtype='<U21'))

In [12]:
e = np.array(([1,2,3],[4,5,6]))
e

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c = np.arange(3,20,3)
c

array([ 3,  6,  9, 12, 15, 18])

In [14]:
c = np.sqrt(([50,5,30,25]))
c

array([7.07106781, 2.23606798, 5.47722558, 5.        ])

In [15]:
c = np.array([1.365,2.635,3.5896])
np.around(c,2)

array([1.36, 2.64, 3.59])

In [16]:
e.sum(axis = 1), e.sum(axis = 0)

(array([ 6, 15]), array([5, 7, 9]))

In [17]:
# define two matrices
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[7,8,9],[10,11,12]])
A


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
A.T, B.T

(array([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]]),
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]))

In [19]:
A[0:0]

array([], shape=(0, 3), dtype=int64)

In [20]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [21]:
type(b)

numpy.ndarray

In [22]:
!pip install pytype


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.3/210.3 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 23.0 MB/s eta 0:00:00
  Attempting uninstall: networkx
    Found existing installation: networkx 3.3
    Uninstalling networkx-3.3:
      Successfully uninstalled networkx-3.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.2.1+cu121 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.2.1+cu121 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", whic

In [23]:
TypeError(b)

TypeError(array([1, 2, 3, 4]))

In [24]:
# Example: Getting the type name of various objects

# Integer type
x = 5
print(type(x).__name__)

# List type
y = [1, 2, 3]
print(type(y).__name__)

# Custom class
class Car:
    pass

my_car = Car()
print(type(my_car).__name__)


int
list
Car


In [25]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [26]:
a.ndim

1

In [27]:
a.shape, a.size

((4,), 4)

In [28]:
b.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [29]:
type(b), b.ndim, b.shape

(numpy.ndarray, 1, (4,))

In [30]:
c = np.arange(3,10)
c

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
print(c.ndim),c.shape

1


(None, (7,))

In [32]:
c.astype(str)

array(['3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [33]:
print(np.around(np.sqrt(c),2)); print(np.arange(9))

[1.73 2.   2.24 2.45 2.65 2.83 3.  ]
[0 1 2 3 4 5 6 7 8]


In [34]:
a1 = np.array(([1,2,3],[4,5,6]))
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a1.ndim

2

In [36]:
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a1.shape

(2, 3)

In [38]:
a1.dtype

dtype('int64')

In [39]:
a1.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
a1.sum(axis = 1), a1.sum(axis = 0)

(array([ 6, 15]), array([5, 7, 9]))

In [41]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
np.mean(a1,axis=0)

array([2.5, 3.5, 4.5])

In [44]:
np.fill_diagonal(a1,0)
a1

array([[0, 2, 3],
       [4, 0, 6]])

In [45]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [46]:
c = np.matmul(A, B)

In [47]:
A.T, B.T


(array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]))

In [48]:
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])

a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [50]:
a4[1][2], a4[3][1]

(8, 9)

In [49]:
a4[0:2]

array([[3, 4, 5],
       [7, 2, 8]])

In [51]:
a4[2]

array([9, 1, 6])

In [52]:
for i in a4:
  print(i[2])
  print(i[0:2])

5
[3 4]
8
[7 2]
6
[9 1]
18
[10  9]


In [53]:
[i[1] for i in a4]

[4, 2, 1, 9]

In [54]:
for i in a4:
  print(i[1])

4
2
1
9


In [55]:
[i[1] for i in a4]

[4, 2, 1, 9]

In [59]:
a4[1:,2:]

array([[ 8],
       [ 6],
       [18]])

In [60]:
np.argmax(a4,axis = 1), np.argmax(a4,axis = 0)

(array([2, 2, 0, 2]), array([3, 3, 3]))

In [61]:
np.max(a4, axis = 0), np.max(a4, axis = 1)

(array([10,  9, 18]), array([ 5,  8,  9, 18]))

In [62]:
a1 = np.array([1,2,3])
a2 = np.array([3,8,9])
a1+a2

array([ 4, 10, 12])

In [64]:
a2-a1

array([2, 6, 6])

In [65]:
a1*a2

array([ 3, 16, 27])

In [66]:
a2/a1

array([3., 4., 3.])

In [67]:
a1**a2

array([    1,   256, 19683])

In [68]:
a1,a2

(array([1, 2, 3]), array([3, 8, 9]))

In [69]:
np.logical_and(a1,a2)

array([ True,  True,  True])

In [70]:
a1 & a2

array([1, 0, 1])

In [73]:
np.logical_not(a1,a2)

array([0, 0, 0])

In [74]:
np.logical_xor(a1,a2)

array([ True,  True,  True])

In [75]:
np.logical_or(a1,a2)

array([ True,  True,  True])